codecov:
  require_ci_to_pass: no

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
        flags:
          - integration
    patch:
      default:
        target: 85%
        threshold: 1%
    changes: false

flags:
  integration:
    paths:
      - src/scviva/
    carryforward: false
  cuda:
    paths:
      - src/scviva/
    carryforward: true
  macos:
    paths:
      - src/scviva/
    carryforward: true

comment:
  layout: diff, flags, files
  behavior: once
  require_base: no
