blank_issues_enabled: false
contact_links:
  - name: scvi-tools documentation
    url: https://docs.scvi-tools.org
    about: scviva-tools is built on scvi-tools. Check their docs for base model questions.
