blank_issues_enabled: false
contact_links:
  - name: Usage Questions
    url: https://discourse.scverse.org/c/help/scvi-tools
    about: Please ask usage questions on the scverse Discourse forum
  - name: Documentation
    url: https://spatialvi-tools.readthedocs.io
    about: Check the documentation for tutorials and API reference
  - name: scvi-tools Issues
    url: https://github.com/scverse/scvi-tools/issues
    about: For issues related to core scvi-tools functionality
