"""Golden-output (characterization) tests for the AnnData-based CCC entry points.

These tests lock in the *current* numeric behavior of the four heavier
AnnData-based cell-cell-communication entry points in
`scviva.tools.harreman.tools.cell_communication`:

- `compute_cell_communication`
- `run_cell_communication_analysis`
- `compute_ct_cell_communication`
- `run_ct_cell_communication_analysis`

Because these functions run seeded permutation tests over sparse/torch
tensors, no one can hand-compute the expected numeric output in advance.
Instead we froze the exact output of the current, unmodified code into a
checked-in `.npz` snapshot (see `data/cell_communication_golden.npz`,
generated by the one-off script referenced in the Task 2 brief) and assert
that new runs match it exactly. This gives later file-splitting/refactor
tasks a safety net: if any of these assertions ever fail, that is a real
behavior change, not a test bug — do not "fix" the test by regenerating the
snapshot without first confirming the change was intentional.

Do not edit this test file after Task 2, except in Task 9/10 where dead-code
deletion or stats consolidation could legitimately change internal call
paths (the golden *values* must not change).
"""

import numpy as np
import pandas as pd
import pytest
from anndata import AnnData

from scviva.tools import HarremanAnalysis
from scviva.tools.harreman.tools.cell_communication import (
    compute_cell_communication,
    compute_ct_cell_communication,
    compute_gene_pairs,
    run_cell_communication_analysis,
    run_ct_cell_communication_analysis,
)

GOLDEN_PATH = __file__.rsplit("/", 1)[0] + "/data/cell_communication_golden.npz"


def _ccc_ready_adata(ct_specific: bool) -> AnnData:
    """8 genes (2 LR pairs), 40 cells, 2 cell types, deterministic kNN graph."""
    n_obs = 40
    gene_names = [f"gene{i}" for i in range(8)]
    rng = np.random.default_rng(0)
    X = rng.poisson(2.0, size=(n_obs, len(gene_names))).astype(float)
    obs = pd.DataFrame(
        {"cell_type": pd.Categorical(["A", "B"] * (n_obs // 2))},
        index=[f"cell{i}" for i in range(n_obs)],
    )
    var = pd.DataFrame(index=gene_names)
    obsm = {"spatial": rng.uniform(0, 100, size=(n_obs, 2))}
    adata = AnnData(X=X, obs=obs, var=var, obsm=obsm)

    database = pd.DataFrame(0.0, index=gene_names, columns=["pair0", "pair1"])
    database.loc["gene0", "pair0"] = 1.0  # ligand
    database.loc["gene1", "pair0"] = -1.0  # receptor
    database.loc["gene2", "pair1"] = 1.0  # ligand
    database.loc["gene3", "pair1"] = -1.0  # receptor
    adata.varm["database"] = database
    adata.uns["database"] = "LR"
    adata.uns["ligand"] = pd.DataFrame({0: ["gene0", "gene2"]}, index=["pair0", "pair1"])
    adata.uns["receptor"] = pd.DataFrame({0: ["gene1", "gene3"]}, index=["pair0", "pair1"])

    HarremanAnalysis(adata).tl.compute_knn_graph(compute_neighbors_on_key="spatial", n_neighbors=5)

    compute_gene_pairs(
        adata,
        cell_type_key="cell_type" if ct_specific else None,
        ct_specific=ct_specific,
        verbose=False,
    )
    return adata


@pytest.fixture(scope="module")
def golden_snapshots():
    return np.load(GOLDEN_PATH, allow_pickle=True)


def test_compute_cell_communication_golden(golden_snapshots):
    adata = _ccc_ready_adata(ct_specific=False)
    # NOTE: model=None (the brief's guessed default) crashes inside
    # standardize_counts -> center_counts_torch, which only recognizes the
    # string literals "bernoulli"/"danb"/"normal"/"none" and raises
    # ValueError("Unsupported model type: None") otherwise. "none" means "no
    # centering" and is the closest equivalent to the brief's intent.
    compute_cell_communication(
        adata,
        model="none",
        M=20,
        seed=0,
        test="both",
        check_analytic_null=False,
        device="cpu",
        verbose=False,
    )
    # NOTE: the real key path (confirmed by reading run_cell_communication_analysis /
    # get_cell_communication_results) is uns["ccc_results"]["p"]["gp"]["cs"] for the
    # primary parametric gene-pair communication score, and
    # uns["ccc_results"]["p"]["gp"]["Z_FDR"] for its significance (FDR-corrected
    # p-value of the Z-score) -- not the ["p"]["scores"]/["p"]["FDR"] paths guessed
    # in the brief.
    expected = golden_snapshots["compute_cell_communication_p_scores"]
    np.testing.assert_allclose(
        adata.uns["ccc_results"]["p"]["gp"]["cs"], expected, rtol=1e-6, atol=1e-8
    )
    expected_fdr = golden_snapshots["compute_cell_communication_p_fdr"]
    np.testing.assert_allclose(
        adata.uns["ccc_results"]["p"]["gp"]["Z_FDR"], expected_fdr, rtol=1e-6, atol=1e-8
    )


def test_run_cell_communication_analysis_golden(golden_snapshots):
    adata = _ccc_ready_adata(ct_specific=False)
    # NOTE: run_cell_communication_analysis is normally only called from inside
    # compute_cell_communication, which pre-initializes uns["ccc_results"] = {}
    # before calling it (see cell_communication.py:617). Called directly (as
    # here), it raises KeyError: 'ccc_results' at the first
    # adata.uns["ccc_results"]["p"] = {...} assignment unless we replicate that
    # setup step ourselves.
    adata.uns["ccc_results"] = {}
    run_cell_communication_analysis(
        adata,
        layer_key_p_test=None,
        layer_key_np_test=None,
        model="none",  # see NOTE in test_compute_cell_communication_golden
        center_counts_for_np_test=False,
        subset_gene_pairs=None,
        M=20,
        seed=0,
        test="both",
        mean="algebraic",
        check_analytic_null=False,
        device="cpu",
        verbose=False,
    )
    # NOTE: uns["lc_zs"] exists exactly as the brief guessed, but it is a pandas
    # DataFrame (symmetric gene x gene Z-score matrix), not a bare ndarray -- the
    # golden snapshot stores its .values, so we compare against .values here too.
    expected = golden_snapshots["run_cell_communication_analysis_lc_zs"]
    np.testing.assert_allclose(adata.uns["lc_zs"].values, expected, rtol=1e-6, atol=1e-8)


def test_compute_ct_cell_communication_golden(golden_snapshots):
    adata = _ccc_ready_adata(ct_specific=True)
    compute_ct_cell_communication(
        adata,
        model="none",  # see NOTE in test_compute_cell_communication_golden
        cell_type_key="cell_type",
        M=20,
        seed=0,
        test="both",
        check_analytic_null=False,
        device="cpu",
        verbose=False,
    )
    # NOTE: same deviation as compute_cell_communication -- real key is
    # uns["ct_ccc_results"]["p"]["gp"]["cs"], not ["p"]["scores"].
    expected = golden_snapshots["compute_ct_cell_communication_p_scores"]
    np.testing.assert_allclose(
        adata.uns["ct_ccc_results"]["p"]["gp"]["cs"], expected, rtol=1e-6, atol=1e-8
    )


def test_run_ct_cell_communication_analysis_golden(golden_snapshots):
    adata = _ccc_ready_adata(ct_specific=True)
    # NOTE: same "ccc_results must be pre-initialized" issue as
    # test_run_cell_communication_analysis_golden, but for ct_ccc_results (see
    # cell_communication.py:1130, compute_ct_cell_communication's setup step).
    adata.uns["ct_ccc_results"] = {}
    run_ct_cell_communication_analysis(
        adata,
        layer_key_p_test=None,
        layer_key_np_test=None,
        model="none",  # see NOTE in test_compute_cell_communication_golden
        cell_type_key="cell_type",
        center_counts_for_np_test=False,
        subset_gene_pairs=None,
        subset_metabolites=None,
        fix_gp=False,
        M=20,
        seed=0,
        test="both",
        mean="algebraic",
        check_analytic_null=False,
        device="cpu",
        verbose=False,
    )
    # NOTE: uns["D"] matches the brief's guess exactly (already an ndarray of
    # per-cell-type-pair spatial node degrees).
    expected = golden_snapshots["run_ct_cell_communication_analysis_D"]
    np.testing.assert_allclose(adata.uns["D"], expected, rtol=1e-6, atol=1e-8)
