name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/scviva-tools
    permissions:
      id-token: write # mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install build tools
        run: pip install hatchling
      - name: Build package
        run: python -m hatchling build
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
